#!/bin/bash
## Job Name
#SBATCH --job-name=temp
## Allocation Definition
#SBATCH --account=chem
#SBATCH --partition=chem
## Resources
## Nodes
#SBATCH --nodes=1
## Tasks per node (28 is Slurm default)
#SBATCH --ntasks-per-node=28
## Walltime (days-HH:MM:SS)
#SBATCH --time=15:00:00
## Memory per node
#SBATCH --mem=80G
##Output file
#SBTACH --output cfs.out

module load anaconda3_4.3.1

# Initial set up & scattering calculation 
gfortran shape.f90 && ./a.out
python input_generator.py -d parameters.input shape.dat
python input_generator.py -v parameters.input shape.dat
wait
/gscratch/chem/masiello_group/src-gaussian/ddscat &> DDA.out &
wait
mv tdda_input_w000_ddscat.par tdda_input
wait
# tDDA calculation
/gscratch/chem/masiello_group/tDDA_1123_sub_plane/Lattice_Diffusion /gscratch/chem/masiello_group/myGreen.num_300 var.par tdda_input temp.out
